### ISSUE TITLE
Implement login page

### ISSUE THREAD

**Issue by ernado-x** [kpi-ua/statistic.campus.kpi.ua#2]

**Comment by ernado-x** [comment]
@MizovOO any progress on this task?

**Comment by ernado-x** [comment]
@MizovOO ?

**Comment by MizovOO** [comment]
Первые 2 страницы уже готовы начал работу над 3.
https://github.com/kpi-ua/statistic.campus.kpi.ua/tree/dev

-- реклама -----------------------------------------------------------
Нужна квартира? Нет сразу денег? Банк не даёт кредит? Вариант есть! 
Рассрочка на готовое жильё! http://www.milayakvartira.kiev.ua/

**Comment by ernado-x** [comment]
А авторизация уже работает?
